### ISSUE TITLE
`TestHttpServerProvider.testStop` is flaky

### ISSUE THREAD

**Issue by haozhun** [airlift/airlift#530] opened 2017-05-18 19:44 UTC
I saw a failure in travis, and tried to reproduce it locally.

I set invocationCount to 1000 and ran it 3 times. I got 1, 0, 3 failures for the 3 runs.

**Comment by nezihyigitbasi** [comment] 2017-05-18 19:48
I guess this is a duplicate of #520.

**Closed** 2017-05-18 19:58 UTC
